# curl -X POST -H "Content-Type:application/json" -d @./sse-source-connect.json http://localhost:8083/connectors
POST http://localhost:8083/connectors
Content-Type: application/json

< ./sse-source-connect.json

###

